[package]
name = "sphinx"
version = "0.0.3"
edition = "2021"

[features]
animation = []

[dependencies]
eframe = "0.18.0"

tracing = "0.1"
thiserror = "1.0"

futures = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }

[dev-dependencies]
tracing-subscriber = "0.3.11"
